# Generated by Django 5.0.6 on 2024-07-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pystore', '0006_banner_remove_product_price_productattribut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribut',
            new_name='ProductAttribute',
        ),
    ]
