# Generated by Django 5.0.6 on 2024-07-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pystore', '0007_rename_productattribut_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='banner_img/'),
        ),
    ]
