# Generated by Django 5.0.6 on 2024-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pystore', '0008_alter_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured_product',
            field=models.BooleanField(default=False),
        ),
    ]
