# Generated by Django 5.0.6 on 2024-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pystore', '0009_product_is_featured_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
