# Generated by Django 5.0.6 on 2024-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pystore', '0011_alter_productattribute_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='photos/')),
                ('category_type', models.CharField(choices=[('cap', 'cap'), ('pants', 'pants'), ('sneakers', 'sneakers'), ('t-shirt', 't-shirt')], default='t-shirt', max_length=20)),
            ],
        ),
    ]
